#server:
#  port: 8096
#  context-path: /springboot
#spring:
#    datasource:
#      type: com.alibaba.druid.pool.DruidDataSource
#      url: jdbc:mysql://localhost:3306/mysql
#      driver-class-name: com.mysql.jdbc.Driver
#      username: root
#      password: 123456
#mybatis:
#    mapper-locations: classpath:com/baizhi/dao/*Mapper.xml
#    type-aliases-package: com.baizhi.entity
#spring:
#  mvc:
#    view:
#      prefix: /
#      suffix: .jsp


server:
  port:2151
  context-path: /springboot
spring:
  datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  url: jdbc:mysql://localhost:3306/ssm
  driver-class-name: com.mysql.jdbc.Driver
  username: root
  password: 123456
mybatis:
  mapper-locations: classpath:com/baizhi/mapping/*Mapper.xml
  type-aliases-package: com.baihi.entity






















